### ISSUE TITLE
Strings with embedded «\"» are not handled correctly

### ISSUE THREAD

**Issue by shlomif** [pboettch/vim-cmake-syntax#1]
Hi!

With this `CMakeLists.txt` file:

```
ADD_DEFINITIONS("-DLOCOFFDIR=\"500\"")

IF ("${NO_OFFENSIVE}")
    ADD_DEFINITIONS("-DNO_OFFENSIVE=1")
ENDIF()

```

The string in the first line extends to the end of the document with this repository's cmake syntax. I can provide a screenshot and perhaps a regression automated test should be written.

Credit is in part due to https://github.com/shlomif/fortune-mod/issues/9 which made me discover it.

**Comment by pboettch** [comment]
I already fixed this last week, but it was before you created the issue. I push-forced a new version of the commit, referencing this issue.

Would you allow a remark concerning your cmake-code with which you detected the problem? You don't need to escape anything in fact. The following works as you'd expect (also consider using lower-case cmake commands as recommended by CMake since 2.8 iirc):

```cmake
add_definitions(-DLOCOFFDIR="500")

if("${NO_OFFENSIVE}")
    add_definitions(-DNO_OFFENSIVE=1)
endif()
````

**Comment by shlomif** [comment]
On Sun, 28 May 2017 23:13:31 -0700
Patrick Boettcher <notifications@github.com> wrote:

> I already fixed this last week, but it was before you created the issue. I
> push-forced a new version of the commit, referencing this issue.
> 
> Would you allow a remark concerning your cmake-code with which you detected
> the problem? You don't need to escape anything in fact. The following works
> as you'd expect (also consider using lower-case cmake commands as recommended
> by CMake since 2.8 iirc):
> 
> ```cmake
> add_definitions(-DLOCOFFDIR="500")
> 
> if("${NO_OFFENSIVE}")
>     add_definitions(-DNO_OFFENSIVE=1)
> endif()
> ````
> 

Thanks, Patrick! Seems to be working fine.

Regards,

	Shlomi

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Parody of "The Fountainhead" - http://shlom.in/towtf

What do you mean by “WDYM”?
    — http://www.shlomifish.org/humour.html

Please reply to list if it's a mailing list post - http://shlom.in/reply .
