### ISSUE TITLE
Use line continuation to improve diffs

### ISSUE THREAD

**Issue by bradking** [pboettch/vim-cmake-syntax#10]
Currently the generated syntax file has content like:

```
syn keyword cmakeKWExternalProject contained
                 \ ...long list...
```

Every time a commit adds something to the list the diff is hard to read because it removes a long list and adds a different long list.  Can the generation be updated to use line continuation to have one entry per line?

**Comment by pboettch** [comment]
You're right, I never took the time to investigate how to break lines in vimscript. Now I know. ;-)

**Comment by bradking** [comment]
Nice, thanks!  See [CMake MR 2500](https://gitlab.kitware.com/cmake/cmake/merge_requests/2500) for the import.
