### ISSUE TITLE
lower-case no syntax highlighting

### ISSUE THREAD

**Issue by zhang-wenchao** [pboettch/vim-cmake-syntax#11]

**Comment by pboettch** [comment]
Do you have an example?

**Comment by zhang-wenchao** [comment]
![image](https://user-images.githubusercontent.com/5770157/49198216-07d45000-f3cd-11e8-8f1b-3760c4fc3eb5.png)

```
cmake_minimum_required(VERSION 3.5.1)

project(lib-iot-client)

set(CMAKE_C_STANDARD 90)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(CMAKE_VERBOSE_MAKEFILE FALSE)

add_subdirectory(serialport)

enable_testing()

add_subdirectory(test)

SET()
```

**Comment by pboettch** [comment]
If it looks like that, there is problem with your VIM configuration. 

What does `set ft?` (filetype) say? Are you sure that the syntax/cmake.vim is in the right place?

This is how your code looks on my vim:

![image](https://user-images.githubusercontent.com/442684/49207271-c172f700-f3b4-11e8-9986-51a05e78d9d5.png)

**Comment by zhang-wenchao** [comment]
I checked the cause of the error, thank you
