### ISSUE TITLE
Conflict with user defined parenthesis highlight group 

### ISSUE THREAD

**Issue by voldikss** [pboettch/vim-cmake-syntax#12]
Thanks for your implementation for this cmake syntax plugin!
I just found this plugin have conflicts with this plugin https://github.com/luochen1990/rainbow (When rainbow is actived, vim-cmake-syntax will not work).

![2019-03-29 18-53-58屏幕截图](https://user-images.githubusercontent.com/20282795/55228050-1b48d800-5254-11e9-8365-302d79b23fb2.png)

And then I removed the rainbow plugin and set the following autocmds (because I like colorful parenthesis...). This time vim-cmake-syntax highlighted some keywords but not all keywords were highlighted.  
```vim
autocmd VimEnter,BufWinEnter * syntax match parens1 /[{}]/   | hi parens1 guifg=#FF00FF
autocmd VimEnter,BufWinEnter * syntax match parens2 /[()]/   | hi parens2 guifg=#DF8700
autocmd VimEnter,BufWinEnter * syntax match parens3 /[<>]/   | hi parens3 guifg=#0087FF
autocmd VimEnter,BufWinEnter * syntax match parens4 /[\[\]]/ | hi parens4 guifg=#00FF5F
```
![2019-03-29 18-52-16屏幕截图](https://user-images.githubusercontent.com/20282795/55228060-23a11300-5254-11e9-93c4-53767d923de8.png)

Do we have solutions to this problem?

After I removed all the autocmds and rainbow plugin, vim-cmake-syntax works perfectly

![2019-03-29 18-56-22屏幕截图](https://user-images.githubusercontent.com/20282795/55228183-7aa6e800-5254-11e9-845e-118540891909.png)

**Comment by pboettch** [comment]
Hmm, this is a duplicate of https://github.com/pboettch/vim-cmake-syntax/issues/5 and according to the comments in the rainbox-plugin its not only cmake.

I'd like to fix it (there), but I don't know how.

On the other hand, in cmake you rarely have encapsulated parentheses, braces or brackets - so coloring them is less justified. IMHO.

**Comment by voldikss** [comment]
Thank you for your responses. 

So I will disable the autocmds for `cmake` files and that would be better~

Since this was discussed in #5, I will close this issue.
