### ISSUE TITLE
Syntax highlighting not working as expected

### ISSUE THREAD

**Issue by samaursa** [pboettch/vim-cmake-syntax#5]
I have syntax highlighting enabled in vim (e.g. C++ files get highlighted properly). However, using this plugin does nothing. I also tried adding this:
```
:autocmd BufRead,BufNewFile *.cmake,CMakeLists.txt,*.cmake.in runtime! indent/cmake.vim
:autocmd BufRead,BufNewFile *.cmake,CMakeLists.txt,*.cmake.in setf cmake
:autocmd BufRead,BufNewFile *.ctest,*.ctest.in setf cmake
```

![image](https://user-images.githubusercontent.com/817849/34913065-f0a9a914-f8c0-11e7-83ff-e90735d14ee9.png)

Is there something I am doing wrong? Perhaps missing a setting?

**Comment by pboettch** [comment]
Which version of vim are you using? Normally the cmake-filetype is already included in vim since some time so there is no need for all these `:autocmd` 

Have you checked that when you open a CMakeLists.txt (or a .cmake) the `:set ft?` return cmake?

Can you try the plugin in a clean vim-environnement? So with an (empty) .vimrc and .vim only with the plugin?

**Comment by samaursa** [comment]
>> Which version of vim are you using?

I was using v7.4 and then upgraded to v8.0 hoping that it would fix the issue.

>> Which version of vim are you using? Normally the cmake-filetype is already included in vim since some time so there is no need for all these `:autocmd`

That's what I was thinking as well, since it works out of the box on my Windows machine. However, since it wasn't working, I thought I'd make sure it's picking up the correct file type.

>> Can you try the plugin in a clean vim-environnement? So with an (empty) .vimrc and .vim only with the plugin?

Did that too. Used your `test` directory which opened up a clean environment. Now I'm thinking maybe it's not a clean environment. I'll clean my vim environment completely and start fresh.

**Comment by samaursa** [comment]
Found the culprit! It's https://github.com/kien/rainbow_parentheses.vim plugin. Even with a clean environment, since the plugin was installed, it was doing _something_, which I didn't expect. Either way, the two plugins conflict with each other when it comes to `CMake` files. I'll disable the other plugin for now.

**Comment by pboettch** [comment]
Hmm, wouldn't it be good to understand why this syntax-highlighting break the rainbox-parentheses-plugin?

**Comment by samaursa** [comment]
I agree, let me know how I can help.

Both the following plugins that color the brackets break the syntax highlighting:
https://github.com/kien/rainbow_parentheses.vim
https://github.com/luochen1990/rainbow

For `rainbow_parentheses`, I have to restart `vim` with it turned off. The one from `luochen1990`, I can toggle it which fixes the highlighting.

I tried to disable `rainbow` for `CMake` files only but I am a novice with `vim` and couldn't figure it out (should have been as simple as `if &ft != "cmake"` but that didn't work).

**Comment by offa** [comment]
**Related:** https://github.com/luochen1990/rainbow/issues/77 

See https://github.com/luochen1990/rainbow/issues/77#issuecomment-360254094 for a **_workaround_**.

**Comment by pboettch** [comment]
Yeah, a whole lot of syntax-highlighting-scripts stop to work when a rainbox-parens-plugin is used.
