### ISSUE TITLE
vim-disapprove-deep-indentation Problem In Cmake File

### ISSUE THREAD

**Issue by umitkablan** [pboettch/vim-cmake-syntax#6]
Hi,

I know the problem title yields the fact that it should be targeted to  @doodie since it fails to appropriately show deep indentation in cmake BUT dodie/vim-disapprove-deep-indentation seems to do the same thing and it works for other filetypes I tried. Besides I thought you are the syntax experts to direct me to a correct route.

When I open a cmake file every line is shown with a deep indentation conceal. I binary searched cmake syntax and [this](https://github.com/pboettch/vim-cmake-syntax/blob/master/syntax/cmake.vim#L36) line seems to cause trouble but it also seems to do the whole thing! I tried to delete ALLBUT etc. from it but didn't work.

Could you please show me a way to fix it or give me an idea?

Best,

**Comment by pboettch** [comment]
Could you show an example/screenshot of what you got and what you want?

**Comment by umitkablan** [comment]
Expected:
![cmake_vim_capture_expected](https://user-images.githubusercontent.com/1684909/36063950-e7c87da4-0e94-11e8-9b8f-6d58a805e41f.png)

Got:
![cmake_vim_capture_got](https://user-images.githubusercontent.com/1684909/36063953-f816aae6-0e94-11e8-8761-0f6ba945b470.png)

**Comment by pboettch** [comment]
Looking at the example given by doodie (the scala one) it does the same there with the `map(...)`-function. Why does the `disapprove` warn in this case, maybe it is the same here for cmake?

**Comment by pboettch** [comment]
And the README is saying:

> Conceal depends on modifying the syntax highlighting rules. For some file types and syntax settings, the rules defined in this plugin may conflict with the default rules applied for a filetype, making the look of disapproval appear in the beginning of shallowly indented lines as well. In the case you encounter this issue, feel free to open an issue. Until it's fixed, you can disable the plugin for the problematic file types with the following command:In the case you encounter this issue, feel free to open an issue.

**Comment by umitkablan** [comment]
Sorry that it didn't get my attention - will open a ticket there.

Thanks!
