### ISSUE TITLE
Does not highlight properly when turning a multiline comment off

### ISSUE THREAD

**Issue by gunslingerfry** [pboettch/vim-cmake-syntax#7]
This is extremely minor but I was watching Daniel Pfeifer's 'Effective CMake' presentation and he mentioned this trick.

Trivial example:
```
cmake_minimum_required(VERSION 3.1 FATAL_ERROR)
##[=[
cmake_minimum_required(VERSION 4.0 FATAL_ERROR) # Should not be greyed out
#]=]
```

**Comment by pboettch** [comment]
Everything is extremely minor compared to real problems, nevertheless it would be nice to fix.

I must say the I was not aware of this feature: Commenting out multi-line bracket-comments with single comments. I will dig into it. Thanks for reporting.

**Comment by pboettch** [comment]
What about 

```
#  some text #[=[
cmake_minimum_required(VERSION 4.0 FATAL_ERROR)
]=]```

and

``` 
#  some text #[=[
cmake_minimum_required(VERSION 4.0 FATAL_ERROR)
# ]=]```

How should it behave?

**Comment by gunslingerfry** [comment]
That's a good question. Based on my reading of the cmake language
documentation
<https://cmake.org/cmake/help/v3.0/manual/cmake-language.7.html#comments>,
it would *seem *that bracket comments (aka multiline comments) can appear
anywhere a line comment can. They can also be nested. e.g.
```
##[=[
# active code here
#[==[
# inactive comments
#]==]
#]=]
```
I don't think the # is required for the multiline comment but to facilitate
the easy enabling/disabling of multiline comments.

**Comment by gunslingerfry** [comment]
In the first case there would be a spare closing bracket. In the second case, both brackets would be commented. That's assuming a left to right parsing.

**Comment by pboettch** [comment]
Could you please try the implementation I just pushed? I actually learned about bracket-arguments and comment just now. Thanks again for reporting.
